### ISSUE TITLE
Genes are truncated after zooming in

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-plugin-gdc#57]
![image](https://user-images.githubusercontent.com/83305007/133261753-b3abe136-6b90-43e9-9303-d22df9e1caee.png)

Seen at:
before zooming in 3:133,819,970..134,096,186, after zooming in: 3:133,889,024..134,027,132

Occasionally, when zooming in on a gene on the GDC track, the gene will become truncated/cut off. Zooming in should preserve the gene sequence in its entirety without loss of data displayed.

**Comment by cmdcolin** [comment]
is the query for the genes properly done? it appears to do something like this


0: {op: ">=", content: {field: "genes.gene_start", value: 133,717,978}}
1: {op: "<=", content: {field: "genes.gene_end", value: 133,988,870}}
2: {op: "=", content: {field: "genes.gene_chromosome", value: ["3"]}}
op: "and"


that may only strictly get features that are inside the boundary rather than genes that are overlapping the boundary

i find myself at this page a lot, it may be helpful https://eli.thegreenplace.net/2008/08/15/intersection-of-1d-segments


to be a little more precise, you have

gene.gene_start>=block_start
gene.gene_end<=block_end

you may want something more like this

gene.gene_end >= block_start
gene.gene_start <= block_end
